# Generated by Django 4.2.5 on 2023-09-07 17:33

from django.db import migrations

from sports_league.users.notification_types import UserVerificationNotification


def add_user_verification_email(apps, scheme_editor):
    EmailTemplate = apps.get_model("common", "EmailTemplate")
    EmailTemplate.objects.update_or_create(
        code=UserVerificationNotification.email_slug,
        defaults={
            "template": "Please verify your email with this code {{ code }}",
            "subject": "Verify Your Email"
        }
    )


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_user_verification_email)
    ]
